---
- name: configure .vimrc
  copy: src=../files/.vimrc dest=~vagrant/.vimrc owner=vagrant group=vagrant mode=0700
  tags: vim

- name: configure .bashrc
  copy: src=../files/.bashrc dest=~vagrant/.bashrc owner=vagrant group=vagrant mode=0700
  tags: bashrc

- name: source .bashrc
  shell: source ~vagrant/.bashrc
  tags: bashrc