---
- include: epel.yml
- include: common-packages.yml
# - include: sshd.yml
# - include: ntp.yml
- include: easy_install.yml
- include: dotfiles.yml
- include: language.yml
- include: set-repo-priorities.yml
