---
- name: setting epel priority
  ini_file: dest=/etc/yum.repos.d/epel.repo section="epel" option="priority" value="2"
  tags: priority

- name: setting base priority
  ini_file: dest=/etc/yum.repos.d/CentOS-Base.repo section="base" option="priority" value="1"
  tags: priority
  
- name: setting updates priority
  ini_file: dest=/etc/yum.repos.d/CentOS-Base.repo section="updates" option="priority" value="2"
  tags: priority
  
- name: setting extras priority
  ini_file: dest=/etc/yum.repos.d/CentOS-Base.repo section="extras" option="priority" value="2"
  tags: priority
  
- name: setting centosplus priority
  ini_file: dest=/etc/yum.repos.d/CentOS-Base.repo section="centosplus" option="priority" value="2"
  tags: priority
  
- name: setting contrib priority
  ini_file: dest=/etc/yum.repos.d/CentOS-Base.repo section="contrib" option="priority" value="2"
  tags: priority