---
- name: configure sshd_config
  lineinfile: dest=/etc/ssh/sshd_config owner=root group=root mode=0600 backup=yes {{item}}
  with_items:
    - regexp='^PasswordAuthentication' line='PasswordAuthentication yes' insertafter='#PasswordAuthentication'
    - regexp='^PermitRootLogin' line='PermitRootLogin yes' insertafter='#PermitRootLogin'
    - regexp='^GSSAPIAuthentication' line='GSSAPIAuthentication yes' insertafter='#GSSAPIAuthentication'
  notify: restart sshd
  tags: sshd
